export { default as AdminLayout  } from './AdminLayout'
export { default as Dashboard } from './Dashboard'
export { default as ManageOrders } from './ManageOrder'
export { default as ManageProducts } from './ManageProducts'
export { default as ManageUser } from './ManageUser'
export { default as CreateProduct } from './CreateProducts';
export { default as ManageCategories } from './ManageCategories';
export { default as AdminOrderDetail } from './AdminOrderDetail';
export { default as AdminPersonal } from './AdminPersonal';
export { default as ReportRevenue } from './ReportRevenue';
export { default as ReportInventory } from './ReportInventory';